<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Mukeshs-MacBook-Air.local" failures="1" tests="11" name="PetTests" time="27.696" errors="0" timestamp="2025-05-12T14:50:33 IST">
  <testcase classname="api.test.DataDrivenTests" name="testPostUser" time="5.561"/>
  <testcase classname="api.test.DataDrivenTests" name="testPostUser" time="1.319"/>
  <testcase classname="api.test.DataDrivenTests" name="testPostUser" time="1.344"/>
  <testcase classname="api.test.UserTests" name="testPostUser" time="1.478"/>
  <testcase classname="api.test.UserTests" name="testGetUserByName" time="1.359"/>
  <testcase classname="api.test.UserTests" name="testUpdateUserByName" time="2.725"/>
  <testcase classname="api.test.UserTests" name="testDeleteUserByName" time="1.491"/>
  <testcase classname="api.test.UserTests2" name="testPostUser" time="1.476"/>
  <testcase classname="api.test.UserTests2" name="testGetUserByName" time="1.358">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;404&amp;gt; but was:&amp;lt;200&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<404> but was:<200>
at api.test.UserTests2.testGetUserByName(UserTests2.java:64)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.test.UserTests2" name="testUpdateUserByName" time="2.608"/>
  <testcase classname="api.test.UserTests2" name="testDeleteUserByName" time="1.312"/>
</testsuite> <!-- PetTests -->
